const LANGUAGES = {
    en: {
        setup: {
            title: "Setup",
            addPlayer: "+ Player",
            startShow: "Start Show",
            namePlaceholder: "Name"
        },
        ui: {
            turn: "'s Turn",
            yourTurn: "YOUR TURN",
            rollDice: "Your turn! Tap the dice to roll.",
            botPlaying: "is playing...",
            manage: "Manage Properties",
            trade: "Trade",
            fullscreen: "FULLSCREEN",
            pay: "Pay Now",
            ok: "OK",
            cancel: "Cancel",
            yes: "Yes",
            no: "No",
            close: "Close",
            balance: "Balance",
            wait: "Processing...",
            rent: "Rent",
            houseCost: "House Cost",
            mortgage: "Mortgage",
            unmortgage: "Unmortgage",
            sell: "Sell",
            build: "Build",
            sellHouse: "Sell House",
            bankruptcy: "BANKRUPTCY!",
            gameOver: "GAME OVER! {name} went bankrupt! The music empire collapsed.",
            restart: "Restart Game",
            opportunity: "Opportunity!",
            auction: "Auction",
            buy: "Buy",
            insufficientFunds: "Insufficient Funds",
            pass: "Pass",
            bid: "Bid",
            currentBid: "Current Bid",
            leader: "Leader",
            noOne: "No one",
            startingBid: "Starting Bid",
            payment: "PAYMENT",
            from: "From",
            to: "To",
            amount: "Amount",
            negotiation: "Negotiation Center",
            offerMoney: "Money to offer ($)",
            offerProps: "Properties to give",
            receiveMoney: "Money to receive ($)",
            receiveProps: "Properties to receive",
            makeOffer: "Make Offer ➤",
            reject: "Reject",
            accept: "Accept",
            counter: "Counter-Offer",
            reviewing: "is reviewing...",
            tradeTitle: "Choose a Partner",
            tradeSub: "Who do you want to trade with?",
            tradePropHeader: "Trading: {prop}",
            tradePropSub: "Choose a partner to offer this property:",
            manageTitle: "Your Properties",
            noProps: "You don't own any properties.",
            mortgaged: "(MORTGAGED)",
            stadiums: "Stadiums",
            railRent: ["1 Stadium", "2 Stadiums", "3 Stadiums", "4 Stadiums"],
            utilRent: "If one utility is owned, rent is 4x dice.<br>If both are owned, it's 10x dice.",
            start: "START",
            jail: "STOLEN MASTERS",
            parking: "HIATUS",
            gotoJail: "SOLD MASTERS",
            tax: "INCOME TAX",
            taxDesc: "PAY $100",
            luxury: "Buyback Masters",
            utility: "Taylor's Version",
            chance: "CHANCE OR FATE",
            alert: "Alert",
            you: "(You)",
            insufficientFundsOffer: "You don't have enough money for this offer!",
            proposalRejected: "Proposal Rejected",
            negotiationCancelled: "The negotiation has been cancelled.",
            analyzing: "Analyzing proposal..."
        },
        logs: {
            passedGo: "Passed GO! +$200",
            jailEnter: "3 Doubles! Go to Hiatus!",
            jailLeave: "Out of Hiatus!",
            jailStay: "Still in Hiatus ({turns})",
            rentPaid: "paid ${amount} to {recipient}.",
            auctionWon: "{name} won the auction for {prop} for ${amount}!",
            auctionCancel: "Auction cancelled (no participants).",
            tradeRej: "Trade rejected.",
            tradeAcc: "Trade accepted!",
            bought: "{name} bought {prop} for ${amount}."
        },
        cards: [
            "The Eras Tour Opening Night! Advance to START and begin the show! (+$200)",
            "Masters sold without consent! Go directly to Stolen Masters (Jail).",
            "Private Jet Ready! Advance to the next Eras Tour City (Railroad).",
            "Vinyl Sales Record! Receive $200.",
            "Post-show Exhaustion. Pay $50 for vitamins.",
            "Merch sold out! Receive $50.",
            "Golden Ticket! You got your masters back for free. Use to leave jail.",
            "Surprise Album Drop! Collect $50 from every fan (player).",
            "Taylor's Version outsold the original! Receive $1000 royalties.",
            "Won lawsuit against DJ. Receive $20 symbolic damages.",
            "Secret Session with Fans! Receive $10 from each.",
            "Signed millionaire contract with Republic Records. Receive $1000.",
            "Late for stage fine. Pay $100.",
            "Bought new Versace costumes. Pay $50.",
            "Wrote a song for another artist. Receive $25.",
            "Stadium Renovations. Pay $40 per house and $115 per hotel.",
            "TIME Person of the Year Cover! Receive $10.",
            "Official Fan Club grew. Receive $100.",
            "Go take a walk on 'The Life of a Showgirl'. You got this.",
            "Existential Crisis. Advance to 'Anti-Hero'. It's me, hi!"
        ]
    },
    de: {
        setup: {
            title: "Einstellungen",
            addPlayer: "+ Spieler",
            startShow: "Show Starten",
            namePlaceholder: "Name"
        },
        ui: {
            turn: "ist dran",
            yourTurn: "DU BIST DRAN",
            rollDice: "Du bist dran! Tippe auf die Würfel.",
            botPlaying: "spielt...",
            manage: "Eigentum verwalten",
            trade: "Handeln",
            fullscreen: "VOLLBILD",
            pay: "Jetzt zahlen",
            ok: "OK",
            cancel: "Abbrechen",
            yes: "Ja",
            no: "Nein",
            close: "Schließen",
            balance: "Guthaben",
            wait: "Verarbeitung...",
            rent: "Miete",
            houseCost: "Hauskosten",
            mortgage: "Hypothek",
            unmortgage: "Hypothek auflösen",
            sell: "Verkaufen",
            build: "Bauen",
            sellHouse: "Haus verkaufen",
            bankruptcy: "BANKROTT!",
            gameOver: "GAME OVER! {name} ist bankrott! Das Musikimperium ist zusammengebrochen.",
            restart: "Neustarten",
            opportunity: "Gelegenheit!",
            auction: "Auktion",
            buy: "Kaufen",
            insufficientFunds: "Zu wenig Geld",
            pass: "Passen",
            bid: "Bieten",
            currentBid: "Aktuelles Gebot",
            leader: "Führender",
            noOne: "Niemand",
            startingBid: "Startgebot",
            payment: "ZAHLUNG",
            from: "Von",
            to: "An",
            amount: "Betrag",
            negotiation: "Verhandlungszentrum",
            offerMoney: "Geld anbieten ($)",
            offerProps: "Eigentum geben",
            receiveMoney: "Geld erhalten ($)",
            receiveProps: "Eigentum erhalten",
            makeOffer: "Angebot machen ➤",
            reject: "Ablehnen",
            accept: "Akzeptieren",
            counter: "Gegenangebot",
            reviewing: "überprüft...",
            tradeTitle: "Partner wählen",
            tradeSub: "Mit wem möchtest du handeln?",
            tradePropHeader: "Handel: {prop}",
            tradePropSub: "Wähle einen Partner für dieses Eigentum:",
            manageTitle: "Dein Eigentum",
            noProps: "Du besitzt kein Eigentum.",
            mortgaged: "(BELIEHEN)",
            stadiums: "Stadien",
            railRent: ["1 Stadion", "2 Stadien", "3 Stadien", "4 Stadien"],
            utilRent: "Wenn 1 Versorgungswerk, Miete = 4x Würfel.<br>Wenn beide, Miete = 10x Würfel.",
            start: "START",
            jail: "GESTOHLENE MASTERS",
            parking: "HIATUS",
            gotoJail: "VERKAUFTE MASTERS",
            tax: "EINKOMMENSSTEUER",
            taxDesc: "ZAHLEN $100",
            luxury: "Buyback Masters",
            utility: "Taylor's Version",
            chance: "CHANCE ODER SCHICKSAL",
            alert: "Hinweis",
            you: "(Du)",
            insufficientFundsOffer: "Du hast nicht genug Geld für dieses Angebot!",
            proposalRejected: "Vorschlag abgelehnt",
            negotiationCancelled: "Die Verhandlung wurde abgebrochen.",
            analyzing: "Untersuche Vorschlag..."
        },
        logs: {
            passedGo: "Über START! +$200",
            jailEnter: "3 Paschs! Ab ins Hiatus!",
            jailLeave: "Raus aus dem Hiatus!",
            jailStay: "Noch im Hiatus ({turns})",
            rentPaid: "zahlte ${amount} an {recipient}.",
            auctionWon: "{name} gewann die Auktion für {prop} für ${amount}!",
            auctionCancel: "Auktion abgebrochen (keine Teilnehmer).",
            tradeRej: "Handel abgelehnt.",
            tradeAcc: "Handel akzeptiert!",
            bought: "{name} kaufte {prop} für ${amount}."
        },
        cards: [
            "The Eras Tour Opening Night! Gehe auf START und beginne die Show! (+$200)",
            "Masters ohne Zustimmung verkauft! Gehe direkt zu den Gestohlenen Masters (Gefängnis).",
            "Privatjet bereit! Gehe zur nächsten Eras Tour Stadt (Bahnhof).",
            "Vinyl-Verkaufsrekord! Erhalte $200.",
            "Erschöpfung nach der Show. Zahle $50 für Vitamine.",
            "Merch ausverkauft! Erhalte $50.",
            "Golden Ticket! Du hast deine Masters zurück. Frei aus dem Gefängnis.",
            "Überraschungsalbum! Erhalte $50 von jedem Fan (Spieler).",
            "Taylor's Version verkauft sich besser als das Original! Erhalte $1000 Tantiemen.",
            "Klage gegen DJ gewonnen. Erhalte $20 symbolischen Schadenersatz.",
            "Secret Session mit Fans! Erhalte $10 von jedem.",
            "Millionenvertrag mit Republic Records. Erhalte $1000.",
            "Zu spät auf der Bühne. Zahle $100 STRAFE.",
            "Neue Versace-Kostüme gekauft. Zahle $50.",
            "Song für einen anderen Künstler geschrieben. Erhalte $25.",
            "Stadion-Renovierung. Zahle $40 pro Haus und $115 pro Hotel.",
            "TIME Person of the Year Cover! Erhalte $10.",
            "Offizieller Fan Club gewachsen. Erhalte $100.",
            "Geh spazieren auf 'The Life of a Showgirl'. Du schaffst das.",
            "Existenzkrise. Gehe zu 'Anti-Hero'. It's me, hi!"
        ]
    }
};
